version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'severstal-notes-postgresql-database'
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - 'postgres_storage:/data'
    environment:
      - 'POSTGRES_DB=${DATABASE_NAME}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${DATABASE_USER}'

  minio:
    image: 'minio/minio:latest'
    container_name: 'severstal-images-storage-minio'
    ports:
      - '${MINIO_PORT}:9000'
    volumes:
      - 'minio_storage:/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ACCESS_KEY}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}'
      - 'MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET}'
    command: server /data

  create-bucket:
    image: 'minio/minio:latest'
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set severstal-images-storage-minio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb severstal-images-storage-minio/storage;
      /usr/bin/mc policy set public severstal-images-storage-minio/storage;
      exit 0;
      "

volumes:
  postgres_storage: {}
  minio_storage: {}