CREATE TABLE IF NOT EXISTS users (
   id SERIAL PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS notes (
   id SERIAL PRIMARY KEY,
   title VARCHAR(255) NOT NULL UNIQUE,
   content TEXT,
   create_at TIMESTAMP NOT NULL,
   owner_id BIGINT NOT NULL,
   CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);